spring.application.name=PixayAPI

server.port=8081

spring.datasource.url=jdbc:h2:file:./data/pixay-db;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
# spring.jpa.hibernate.ddl-auto=create
#TODO update solo para desarrollo, luego lo ponemos a =none
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.defer-datasource-initialization=true
# cómo en la bdd tenemos el MERGE no va a dar problemas por tenerlo en always
spring.sql.init.mode=always
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

JWT_SECRET=VGhpcy1pcy1hLXZlcnktbG9uZy1hbmQtc2VjdXJlLWtleS1mb3ItSldULXRva2Vucw==
JWT_EXPIRATION=24


# Tamano maximo del archivo (ej. 5MB)
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB